### ISSUE TITLE
app not work

### ISSUE THREAD

**Issue by Zebra67** [shrimp509/BrightnessKing#5]
Hello I installed application from playstore but application not work please check

**Comment by shrimp509** [comment]
@Zebra67 Hi, glad to hear from your feedback. Could you please offer your information below?
- device brand and model
- android version
- what situation (brightness bar doesn't show up or can't adjust brightness through brightness bar)

**Comment by Zebra67** [comment]
1) Redmi note 7 pro
2) ver-9 
3) popup bar show on which we have to slide left/right for brightness,  but brightness didn't increase/decrease.
please check

**Comment by shrimp509** [comment]
OK, in my guess, this is maybe `auto brightness problem`.
The first problem solving way is to disable `Automatic brightness`.
You can reference to this video: https://www.youtube.com/watch?v=Jz-MGniLxV8

Any problem or question is welcome.

**Comment by Zebra67** [comment]
No sir, I already tried this but still same problem.

**Comment by shrimp509** [comment]
OK, I'll try to borrow redmi asap.
May not solve your problem in these weeks. (I don't have friends 😭)
Please be patient, and thanks your report!

**Comment by shrimp509** [comment]
Hi @Zebra67 ,
I did fix the bugs in xiaomi mix 2 (android 9), but I am not really sure that it is also available for redmi pro 7. Please use the v1.2.3 aab file to test in your device for confirmation. Here is the link: https://github.com/shrimp509/BrightnessKing/releases
Or you can wait the next update in google play. (maybe two to seven days later for review of google play)

If this problem still not being fixed, just reopen the issue.

**Comment by Zebra67** [comment]
ok , how to install .aab file on phone?

**Comment by shrimp509** [comment]
Here you are
https://stackoverflow.com/questions/50419286/install-android-app-bundle-on-device
